# Generated by Django 2.2.1 on 2019-06-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cinema", "0005_auto_20190602_1622")]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE cinema_film ALTER COLUMN title "
            + 'TYPE varchar(120) COLLATE "en-x-icu";'
        )
    ]
